In [97]:
import dask.dataframe as dd
import dask.array as da
import numpy as np
import pandas as pd

In [71]:
df = dd.read_csv("C:\\NYCOpendata\\StatenIsland.csv",error_bad_lines=False)

In [72]:
dcompl = df[['Complaint Type','Descriptor']]

In [73]:
dcompl

Dask DataFrame Structure:
              Complaint Type Descriptor
npartitions=9                          
                      object     object
                         ...        ...
...                      ...        ...
                         ...        ...
                         ...        ...
Dask Name: getitem, 36 tasks

In [74]:
dcompl = dcompl.head(100)

In [76]:
dcompl

Complaint Type  \
0                        Water System   
1                               Sewer   
2                        Water System   
3                        Water System   
4                        Water System   
5                        Water System   
6                    Street Condition   
7                    Street Condition   
8                    Street Condition   
9                    Street Condition   
10                   Street Condition   
11                   Street Condition   
12               UNSANITARY CONDITION   
13               UNSANITARY CONDITION   
14                          APPLIANCE   
15                             Rodent   
16                       Building/Use   
17                              Noise   
18                     Standing Water   
19                       Water System   
20                 Water Conservation   
21                       Water System   
22                       Water System   
23                       Water System   
24                       Water System   
25                       Water System   
26                   Street Condition   
27                   Street Condition   
28                   Street Condition   
29                   Street Condition   
..                                ...   
70                   Street Condition   
71                   Street Condition   
72                   Street Condition   
73                   Street Condition   
74                   Street Condition   
75                   Street Condition   
76                   Street Condition   
77             Street Light Condition   
78             Street Light Condition   
79  Missed Collection (All Materials)   
80               UNSANITARY CONDITION   
81                  Other Enforcement   
82                   Dirty Conditions   
83                        DOOR/WINDOW   
84                           ELECTRIC   
85            Litter Basket / Request   
86                           ELECTRIC   
87                         Vacant Lot   
88      General Construction/Plumbing   
89                              Sewer   
90                              Sewer   
91                    FLOORING/STAIRS   
92                              Noise   
93                              Noise   
94                              Noise   
95                              Noise   
96                              Sewer   
97                   Street Condition   
98                   Street Condition   
99                   Street Condition   

                                           Descriptor  
0                         Defective Street Cut (WZZ1)  
1                    Sewer Backup (Use Comments) (SA)  
2                                    Dirty Water (WE)  
3                                    Dirty Water (WE)  
4                           Leak (Use Comments) (WA2)  
5                               Hydrant Leaking (WC1)  
6                                             Pothole  
7                                             Pothole  
8                                             Pothole  
9                                             Pothole  
10                                            Pothole  
11                                            Pothole  
12                          GARBAGE/RECYCLING STORAGE  
13                                              PESTS  
14                                 ELECTRIC/GAS RANGE  
15                       Condition Attracting Rodents  
16   Illegal Conversion Of Residential Building/Space  
17                  Noise:  lawn care equipment (NCL)  
18                       Swimming Pool - Unmaintained  
19                                   Dirty Water (WE)  
20  Water Meter Broken/Leaking - Private Residence...  
21                                   Dirty Water (WE)  
22                              Hydrant Running (WC3)  
23                          Leak (Use Comments) (WA2)  
24                          Leak (Use Comments) (WA2)  
25                      

In [75]:
#dcompl = dcompl.compute()

AttributeError: 'DataFrame' object has no attribute 'compute'

In [77]:
dcompl= dcompl[dcompl['Descriptor'].notnull()]

In [78]:
dcompl.head()

Complaint Type                        Descriptor
0   Water System       Defective Street Cut (WZZ1)
1          Sewer  Sewer Backup (Use Comments) (SA)
2   Water System                  Dirty Water (WE)
3   Water System                  Dirty Water (WE)
4   Water System         Leak (Use Comments) (WA2)

In [79]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5,
                        ngram_range=(1, 2), 
                        stop_words='english')

In [80]:
tfidf

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=5, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=True, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [81]:
tfidf.fit_transform(dcompl['Descriptor'])

<100x13 sparse matrix of type '<class 'numpy.float64'>'
	with 121 stored elements in Compressed Sparse Row format>

In [82]:
from sklearn.feature_selection import chi2
features = tfidf.fit_transform(dcompl['Descriptor']).toarray()
features

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.57735027, 0.57735027,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.53276607],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [83]:
dcompl['complaint_id'] = dcompl['Complaint Type'].factorize()[0]
complaint_id_df = dcompl[['Complaint Type', 'complaint_id']].drop_duplicates()

In [84]:
labels = dcompl.complaint_id

In [85]:
labels

0      0
1      1
2      0
3      0
4      0
5      0
6      2
7      2
8      2
9      2
10     2
11     2
12     3
13     3
14     4
15     5
16     6
17     7
18     8
19     0
20     9
21     0
22     0
23     0
24     0
25     0
26     2
27     2
28     2
29     2
      ..
70     2
71     2
72     2
73     2
74     2
75     2
76     2
77    17
78    17
79    27
80     3
81    19
82    11
83    28
84    13
85    29
86    13
87    16
88    23
89     1
90     1
91    14
92     7
93     7
94     7
95     7
96     1
97     2
98     2
99     2
Name: complaint_id, Length: 100, dtype: int64

In [86]:
dcompl.head()

Complaint Type                        Descriptor  complaint_id
0   Water System       Defective Street Cut (WZZ1)             0
1          Sewer  Sewer Backup (Use Comments) (SA)             1
2   Water System                  Dirty Water (WE)             0
3   Water System                  Dirty Water (WE)             0
4   Water System         Leak (Use Comments) (WA2)             0

In [87]:
k = dcompl[['Complaint Type', 'complaint_id']].drop_duplicates()

In [88]:
k

Complaint Type  complaint_id
0                           Water System             0
1                                  Sewer             1
6                       Street Condition             2
12                  UNSANITARY CONDITION             3
14                             APPLIANCE             4
15                                Rodent             5
16                          Building/Use             6
17                                 Noise             7
18                        Standing Water             8
20                    Water Conservation             9
30                         Water Quality            10
31                      Dirty Conditions            11
32                  Sanitation Condition            12
33                              ELECTRIC            13
34                       FLOORING/STAIRS            14
35                        HEAT/HOT WATER            15
37                            Vacant Lot            16
53                Street Light Condition            17
55                                SAFETY            18
56                     Other Enforcement            19
57                               GENERAL            20
58                         PAINT/PLASTER            21
59                            Electrical            22
60         General Construction/Plumbing            23
61              Traffic Signal Condition            24
64                                  Lead            25
65  Special Natural Area District (SNAD)            26
79     Missed Collection (All Materials)            27
83                           DOOR/WINDOW            28
85               Litter Basket / Request            29

In [89]:
dict(k.values)  #### Converting this into a pyhton disctionary 

{'Water System': 0,
 'Sewer': 1,
 'Street Condition': 2,
 'UNSANITARY CONDITION': 3,
 'APPLIANCE': 4,
 'Rodent': 5,
 'Building/Use': 6,
 'Noise': 7,
 'Standing Water': 8,
 'Water Conservation': 9,
 'Water Quality': 10,
 'Dirty Conditions': 11,
 'Sanitation Condition': 12,
 'ELECTRIC': 13,
 'FLOORING/STAIRS': 14,
 'HEAT/HOT WATER': 15,
 'Vacant Lot': 16,
 'Street Light Condition': 17,
 'SAFETY': 18,
 'Other Enforcement': 19,
 'GENERAL': 20,
 'PAINT/PLASTER': 21,
 'Electrical': 22,
 'General Construction/Plumbing': 23,
 'Traffic Signal Condition': 24,
 'Lead': 25,
 'Special Natural Area District (SNAD)': 26,
 'Missed Collection (All Materials)': 27,
 'DOOR/WINDOW': 28,
 'Litter Basket / Request': 29}

In [90]:
p = dict(k.values)
sorted(p.items())

[('APPLIANCE', 4),
 ('Building/Use', 6),
 ('DOOR/WINDOW', 28),
 ('Dirty Conditions', 11),
 ('ELECTRIC', 13),
 ('Electrical', 22),
 ('FLOORING/STAIRS', 14),
 ('GENERAL', 20),
 ('General Construction/Plumbing', 23),
 ('HEAT/HOT WATER', 15),
 ('Lead', 25),
 ('Litter Basket / Request', 29),
 ('Missed Collection (All Materials)', 27),
 ('Noise', 7),
 ('Other Enforcement', 19),
 ('PAINT/PLASTER', 21),
 ('Rodent', 5),
 ('SAFETY', 18),
 ('Sanitation Condition', 12),
 ('Sewer', 1),
 ('Special Natural Area District (SNAD)', 26),
 ('Standing Water', 8),
 ('Street Condition', 2),
 ('Street Light Condition', 17),
 ('Traffic Signal Condition', 24),
 ('UNSANITARY CONDITION', 3),
 ('Vacant Lot', 16),
 ('Water Conservation', 9),
 ('Water Quality', 10),
 ('Water System', 0)]

In [91]:
k = sorted(p.items())

chi2 selects n features which are having highest value of chi2 statistic

In [92]:
for i,j in k:
    features_chi2 = chi2(features,labels==j)

In [93]:
features_chi2    #### Feature vector after applying chi2 test (which returns values for each feature eliminate features not dependent on our class)

(array([ 0.41371662,  0.41371662,  0.41371662,  1.60728091, 12.80292486,
        24.49688588,  1.05882353,  4.94117647,  0.88235294,  0.10675381,
         1.60728091,  1.60728091, 11.68950962]),
 array([5.20089100e-01, 5.20089100e-01, 5.20089100e-01, 2.04874444e-01,
        3.46077870e-04, 7.44300379e-07, 3.03483664e-01, 2.62241813e-02,
        3.47558037e-01, 7.43870580e-01, 2.04874444e-01, 2.04874444e-01,
        6.28534621e-04]))

In [95]:
features_chi2[1]

array([5.20089100e-01, 5.20089100e-01, 5.20089100e-01, 2.04874444e-01,
       3.46077870e-04, 7.44300379e-07, 3.03483664e-01, 2.62241813e-02,
       3.47558037e-01, 7.43870580e-01, 2.04874444e-01, 2.04874444e-01,
       6.28534621e-04])

In [98]:
 np.argsort(features_chi2[0])

array([ 9,  0,  1,  2,  8,  6,  3, 10, 11,  7, 12,  4,  5], dtype=int64)

In [100]:
for i,j in k:
    features_chi2 = chi2(features,labels==j)
    print(features_chi2)
    indices = np.argsort(features_chi2[0])
    print(indices)
    

(array([0.02368075, 0.02368075, 0.02368075, 0.04929396, 0.06111261,
       0.04366646, 0.06060606, 0.28282828, 0.05050505, 0.09090909,
       0.04929396, 0.04929396, 0.08292434]), array([0.87770001, 0.87770001, 0.87770001, 0.82429642, 0.80474598,
       0.83447539, 0.80554059, 0.59485342, 0.82218677, 0.7630246 ,
       0.82429642, 0.82429642, 0.77337286]))
[ 0  1  2  5  3 10 11  8  6  4 12  9  7]
(array([0.04784478, 0.04784478, 0.04784478, 0.09959392, 0.12347241,
       0.08822408, 0.12244898, 0.57142857, 0.10204082, 0.18367347,
       0.09959392, 0.09959392, 0.16754102]), array([0.82685688, 0.82685688, 0.82685688, 0.7523175 , 0.72529847,
       0.76644713, 0.7263934 , 0.4496918 , 0.74939418, 0.66823514,
       0.7523175 , 0.7523175 , 0.68230649]))
[ 0  1  2  5  3 10 11  8  6  4 12  9  7]
(array([0.02368075, 0.02368075, 0.02368075, 0.04929396, 0.06111261,
       0.04366646, 0.06060606, 0.28282828, 0.05050505, 0.09090909,
       0.04929396, 0.04929396, 0.08292434]), array([0.87770001, 0

In [101]:
for i,j in k:
    features_chi2 = chi2(features,labels==j)
    print(features_chi2)
    indices = np.argsort(features_chi2[0])
    print(indices)
    feature_names = np.array(tfidf.get_feature_names())[indices]
    print(feature_names)

(array([0.02368075, 0.02368075, 0.02368075, 0.04929396, 0.06111261,
       0.04366646, 0.06060606, 0.28282828, 0.05050505, 0.09090909,
       0.04929396, 0.04929396, 0.08292434]), array([0.87770001, 0.87770001, 0.87770001, 0.82429642, 0.80474598,
       0.83447539, 0.80554059, 0.59485342, 0.82218677, 0.7630246 ,
       0.82429642, 0.82429642, 0.77337286]))
[ 0  1  2  5  3 10 11  8  6  4 12  9  7]
['basin' 'catch' 'catch basin' 'dirty water' 'comments' 'use'
 'use comments' 'request' 'noise' 'dirty' 'water' 'street' 'pothole']
(array([0.04784478, 0.04784478, 0.04784478, 0.09959392, 0.12347241,
       0.08822408, 0.12244898, 0.57142857, 0.10204082, 0.18367347,
       0.09959392, 0.09959392, 0.16754102]), array([0.82685688, 0.82685688, 0.82685688, 0.7523175 , 0.72529847,
       0.76644713, 0.7263934 , 0.4496918 , 0.74939418, 0.66823514,
       0.7523175 , 0.7523175 , 0.68230649]))
[ 0  1  2  5  3 10 11  8  6  4 12  9  7]
['basin' 'catch' 'catch basin' 'dirty water' 'comments' 'use'
 'use 

In [102]:
[v for v in feature_names if len(v.split(' ')) == 1]

['street',
 'basin',
 'catch',
 'request',
 'noise',
 'comments',
 'use',
 'pothole',
 'water',
 'dirty']

In [108]:
uni = [v for v in feature_names if len(v.split(' ')) == 2]
print(uni)

['catch basin', 'use comments', 'dirty water']


In [113]:
'pav'.join(uni[-3:])

'catch basinpavuse commentspavdirty water'

In [109]:
 print("  * Most Correlated Unigrams are: %s" %(', '.join(uni[-3:])))

  * Most Correlated Unigrams are: catch basin, use comments, dirty water
